---

name: Terraform
on:
  pull_request:
  push:
    branches:
      - main
env:
  TERRAFORM_PROJECT_DIR: ./tf
jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write # for POST /repos/:owner/:repo/commits/:sha/comments
      pull-requests: write # for POST /repos/:owner/:repo/issues/:issue_number/comments
    outputs:
      status: ${{ steps.plan.outputs.status }}
      plan-output-slug: ${{ env.PLAN_OUTPUT_SLUG }}
    env:
      PLAN_OUTPUT_SLUG: plan-${{ github.job }}-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.1.9'
          terraform_wrapper: false
      - run: terraform init
        working-directory: ${{ env.TERRAFORM_PROJECT_DIR }}
      - uses: ./.github/actions/setup-tfcmt
        with:
          version: '3.2.2-0'
      - name: terraform plan
        env:
          _out_path: ${{ env.PLAN_OUTPUT_SLUG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set +e
          tfcmt plan -- terraform plan -detailed-exitcode -out=$_out_path
          case $? in
          0)
            echo '::set-output name=status::no-changes'
            ;;
          1)
            echo '::set-output name=status::error'
            ;;
          2)
            echo '::set-output name=status::has-diff'
            ;;
          esac
        id: plan
        working-directory: ${{ env.TERRAFORM_PROJECT_DIR }}
      - uses: actions/upload-artifact@v3
        if: ${{ steps.plan.outputs.status == 'has-diff' }}
        with:
          name: ${{ env.PLAN_OUTPUT_SLUG }}
          path: ${{ env.TERRAFORM_PROJECT_DIR }}
          if-no-files-found: error
